name: React Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  react-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build production assets
        run: npm run build
